use super::*;

// Exercise the native PTY reader, not test_process_pty_bytes or a synthetic
// focus-mode event: enabling DECSET 1004 must itself report current focus.
fn assert_initial_focus(
    client_focus: &[Option<bool>],
    never_focused: bool,
    enable_mode: bool,
    repeat_enable: bool,
    expected_hex: &[&str],
) {
    with_terminal_session_test_server(|server, terminal_id, _, _| {
        let pane_id = server.app.state.workspaces[0].tabs[0].root_pane;
        server.app.state.active = Some(0);
        if never_focused {
            let other_tab = server.app.state.workspaces[0].test_add_tab(Some("viewer"));
            assert!(server.app.state.switch_workspace_tab(0, other_tab));
            server.app.state.ensure_test_terminals();
        }
        for (index, focus) in client_focus.iter().enumerate() {
            let client_id = index as u64 + 1;
            let mut client = ClientConnection::new(
                (80, 24),
                crate::kitty_graphics::HostCellSize::default(),
                client_id,
                RenderEncoding::SemanticFrame,
                None,
            );
            client.outer_terminal_focus = *focus;
            server.clients.insert(client_id, client);
        }
        server.foreground_client_id = (!client_focus.is_empty()).then_some(1);
        server.sync_foreground_client_state();
        // Establish the existing focus before the child enables reporting. A
        // later navigation/focus transition must not accidentally satisfy this test.
        server.app.accept_current_focus_without_events();

        // VMIN=0/VTIME=10 bounds each empty read to one second. Reading one byte
        // at a time also handles a focus report fragmented across PTY writes.
        // Keep the child alive after the markers so PaneExited cannot remove
        // the runtime before the test inspects it. shutdown() owns its cleanup.
        let mode = if enable_mode { "h" } else { "l" };
        let rounds = if repeat_enable { 2 } else { 1 };
        let script = format!(
            r#"stty raw -echo min 0 time 10 || exit 1
round=1
while [ "$round" -le {rounds} ]; do
    printf '\033[?1004{mode}'
    hex=$(dd bs=1 count=3 2>/dev/null | od -An -tx1 | tr -d ' \n')
    printf '\r\nFOCUS%s:%s:END\r\n' "$round" "$hex"
    round=$((round + 1))
done
stty min 1 time 0
dd bs=1 count=1 >/dev/null 2>&1
"#
        );
        let runtime = crate::terminal::TerminalRuntime::spawn_argv_command(
            pane_id,
            24,
            80,
            std::env::temp_dir(),
            &["/bin/sh".into(), "-c".into(), script],
            &crate::pane::PaneLaunchEnv::default(),
            crate::pane::AgentDetection::Disabled,
            0,
            crate::terminal_theme::TerminalTheme::default(),
            None,
            server.app.event_tx.clone(),
            server.app.render_notify.clone(),
            server.app.render_dirty.clone(),
        )
        .expect("spawn focus-reporting PTY child");
        server
            .app
            .terminal_runtimes
            .insert(terminal_id.clone(), runtime);

        let deadline = Instant::now() + Duration::from_secs(5);
        let final_marker = format!("FOCUS{rounds}:");
        let (screen, completed) = loop {
            // Match the production server's forwarding boundary. Any new event
            // generated by the real parser will automatically flow through it;
            // these tests compile without naming a not-yet-implemented event.
            while let Ok(event) = server.app.event_rx.try_recv() {
                server.handle_internal_event_with_forwarding(event);
            }
            let runtime = server
                .app
                .terminal_runtimes
                .get(&terminal_id)
                .expect("focus child must stay alive");
            let screen = runtime.detection_text();
            let completed = screen
                .lines()
                .any(|line| line.contains(&final_marker) && line.contains(":END"));
            if completed || Instant::now() >= deadline {
                break (screen, completed);
            }
            std::thread::sleep(Duration::from_millis(5));
        };
        // Clean up before any result assertion, including the expected red
        // assertions on unfixed production code.
        server
            .app
            .terminal_runtimes
            .remove(&terminal_id)
            .expect("owned focus runtime")
            .shutdown();

        assert!(completed, "focus child timed out; screen: {screen:?}");
        assert_eq!(expected_hex.len(), rounds);
        for (index, hex) in expected_hex.iter().enumerate() {
            let marker = format!("FOCUS{}:{hex}:END", index + 1);
            assert!(
                screen.contains(&marker),
                "expected {marker}; screen: {screen:?}"
            );
        }
    });
}

#[test]
fn initial_focus_never_focused_pane_reports_lost() {
    assert_initial_focus(&[Some(true)], true, true, false, &["1b5b4f"]);
}

#[test]
fn initial_focus_focused_client_reports_gained() {
    assert_initial_focus(&[Some(true)], false, true, false, &["1b5b49"]);
}

#[test]
fn initial_focus_without_clients_reports_lost() {
    assert_initial_focus(&[], false, true, false, &["1b5b4f"]);
}

#[test]
fn initial_focus_mode_off_sends_nothing() {
    assert_initial_focus(&[Some(true)], false, false, false, &[""]);
}

#[test]
fn initial_focus_repeated_enable_sends_no_duplicate() {
    assert_initial_focus(&[Some(true)], false, true, true, &["1b5b49", ""]);
}

#[test]
fn initial_focus_other_focused_viewer_reports_gained() {
    // The foreground viewer is unfocused; another viewer still owns focus.
    assert_initial_focus(&[Some(false), Some(true)], false, true, false, &["1b5b49"]);
}

#[test]
fn initial_focus_unknown_outer_focus_reports_lost() {
    assert_initial_focus(&[None], false, true, false, &["1b5b4f"]);
}
